######################################################################
# Automatically generated by qmake (3.0) Mon Aug 21 16:27:06 2017
######################################################################

TEMPLATE = app
TARGET = FriendClass
INCLUDEPATH += .

# Input
HEADERS += test.h
SOURCES += main.cpp test.cpp
